### ISSUE TITLE
Write to tmp file, per boot's idioms

### ISSUE THREAD

**Issue by lwhorton** [mbuczko/boot-build-info#1]
Hey thanks for putting this together. A manifest is something I've needed in nearly every CI pipeline, ever. It's good to see a clojure/boot version already exists.

One thing to note, though, is that the `:dest` path doesn't seem to follow the [boot conventions](https://github.com/boot-clj/boot/wiki/Target-Directory) of only writing to `tmp!` dirs. It would be nice to stick to the convention instead of using java.io to manually write/read to `{out-target}/build-info.json`. 

Does that make sense? For now I can get away with the manual java.io, but it might be useful for others to use boot's fileset filters, `add-resource`, and `commit!`, etc. in tasks that follow the build-info.

**Comment by lwhorton** [comment]
I thought about this a bit more, and I'm not so sure any changes are necessary. Something like the following will work just fine, since ultimately boot-build-info simply accepts an absolute path:

```clojure
(deftask manifest
  "Generate a manifest file for the current build info."
  [n name VAL str "Name of the manifest file to generate (end it with .json)."]
  (let [tmp (c/tmp-dir!)]
    (fn [next-handler]
      (fn [fileset]
        (c/empty-dir! tmp)
        (let [out-path (str (.getAbsolutePath tmp) "/" name)
              next-fs (((build-info/build-info :dest out-path) identity) fileset)]
          (-> next-fs
              (c/add-resource tmp)
              c/commit!
              next-handler))))))
```
We can make our own wrapper task relatively simply that hands build-info one of boot's tmp dirs.

**Comment by mbuczko** [comment]
Hi, thanks for these comments. I agree, this plugin should follow boot conventions and although it's relatively easy to add a workaround I will try to refactor it a bit once I return from vacations :)

**Comment by lwhorton** [comment]
Sounds good, but as I said it’s not *really* necessary. If you are in the mood, it would also be nice to have config flags for that git-sha. I had to scrap the plugin as a whole because the default `git rev-parse —short` could not be overwritten. A lot of the js-world plugins (Webpack, Css compilation, Jenkins CI) use full shas, not short, so it was a hassle.
